### ISSUE TITLE
require is not defined in ES module scope, you can use import instead

### ISSUE THREAD

**Issue by tzwel** [mankins/svelte-adapter-express#10] opened 2022-05-05 18:32 UTC
full log:
`require is not defined in ES module scope, you can use import instead
This file is being treated as an ES module because it has a '.js' file extension and 'D:\projekty2\videohost\my-app\package.json' contains "type": "module". 
To treat it as a CommonJS script, rename it to use the '.cjs' file extension.`

**Comment by mankins** [comment] 2022-05-06 11:04
Duplicate of #9

**Closed as completed by mankins** 2022-05-06 11:04 UTC
